services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - proxy-net

  nginx:
    image: nginx:alpine
    ports: ["8001:80"]
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks: [proxy-net]
    depends_on: [backend]

  apache:
    image: httpd:2.4-alpine
    ports:
      - "8004:80"
    volumes:
      - ./apache/apache.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - proxy-net
    depends_on:
      - backend

  traefik:
    image: traefik:v3.1
    command:
      - "--providers.file.directory=/config"
      - "--entrypoints.web.address=:80"
      - "--log.level=INFO"
    ports: ["8002:80"]
    volumes:
      - ./traefik:/config:ro
    networks: [proxy-net]
    depends_on: [backend]

  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_LOG_LEVEL: "warn"
    volumes: 
      - ./kong:/kong:ro
    ports: ["8003:8000"]
    networks: [proxy-net]
    depends_on: [backend]

  web:
    image: nginx:alpine
    ports: ["8080:80"]
    volumes:
      - ./attack.html:/usr/share/nginx/html/index.html:ro
    networks: [proxy-net]

networks:
  proxy-net:
    driver: bridge